# The URL the site will be built for
base_url = "https://savq.github.io"

# Feed
generate_feed = true
title = "savq"
description = "Sergio A. Vargas' Blog"
default_language = "en"

[markdown]
smart_punctuation = true

highlight_code = true

# Use a different theme for light/dark mode. See ./static/style.css
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" },
]

[extra]
# Put all your custom variables here
